apiVersion: v1
kind: Service
metadata:
  name: odoo-svc
  namespace: icgroup
  labels:
    env: prod
    app: odoo
spec:
  selector:
    app: odoo
  ports:
    - protocol: TCP
      port: 8069
      targetPort: 8069
      nodePort: 30010
  type: NodePort
