apiVersion: v1
kind: Service
metadata:
  name: ic-webapp-svc
  namespace: icgroup
  labels:
    env: prod
    app: ic-webapp
spec:
  selector:
    app: ic-webapp
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30080
  type: NodePort
