apiVersion: v1
kind: ConfigMap
metadata:
  name: pgadmin-cm
  namespace: icgroup
  labels:
    env: prod
    app: pgadmin
data:
  user_email: admin@example.com
  servers.json: |
    {
      "Servers": {
        "1": {
          "Name": "Odoo Database",
          "Group": "IC Group",
          "Port": 5432,
          "Username": "odoo",
          "Password": "myodoo",
          "Host": "postgres-svc",
          "SSLMode": "prefer",
          "MaintenanceDB": "postgres"
        }
      }
    }
